name: build-artifact
on: [push]
jobs:
  linux-builds:
    strategy:
      matrix:
        arch: ['x86', 'x86_64']
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: abel0b/setup-premake@v2.1
        with:
          version: '5.0.0-beta1'
      - run: premake5 gmake
      - run: ${{ format('make -C projects/linux/gmake config=release_{0}', matrix.arch) }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ format('Release {0}', matrix.arch) }}
          path: projects/linux/gmake/**/*.dll